"""make optional the id

Revision ID: f384af651a99
Revises: 43b9bb903d6a
Create Date: 2025-08-01 02:33:32.131236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f384af651a99'
down_revision: Union[str, Sequence[str], None] = '43b9bb903d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mathery', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mathery', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
